ecommerce/CHBS/urls.py
# Author: Taiwo Akinlabi
from django.urls import path
from CHBS import views

# TEMPALTE TAGGING
app_name = 'chbs'

# named urls to their respestive views
urlpatterns = [
    path('', views.home, name='home'),
    path('cart/', views.cart, name='cart'),
    path('menu/', views.menu, name='menu'),
    path('contact/', views.contact, name='contact'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
    path('thank-you/', views.thank_you_view, name='thank-you'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from allauth.account.views import signup, login, logout

urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('', include('CHBS.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/CHBS/models.py
# Author: Taiwo Akinlabi
#Code sourced from : https://www.youtube.com/watch?v=obZMr9URmVI&list=PL-51WBLyFTg0omnamUjL1TCVov7yDTRng&index=2
from django.db import models
from django.contrib.auth.models import User
from decimal import *
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.



# Customer model contains customer field names and property 
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE ,null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    phone = PhoneNumberField(default=False, null=True)

    def __str__(self):
        return str(self.name)

# Product model contains product field names and property 
class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, blank=True, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    special = models.BooleanField(default=False, null=True, blank=True)
    hide = models.BooleanField(default=False, blank=True)
    image = models.ImageField(null=True, blank=True)
    def __str__(self) -> str:
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

# Order model contains order field names and property 
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def get_cart_subtotal(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems]) 
        return round(total, 2)
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        tax = sum([item.get_total for item in orderitems])* Decimal(0.13)
        total = sum([item.get_total for item in orderitems]) + tax
        return round(total, 2)
    
    @property
    def get_cart_tax(self):
        orderitems = self.orderitem_set.all()
        tax = sum([item.get_total for item in orderitems])*Decimal(0.13)
        return round(tax, 2)
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

 # OrderItems model contains orderItems field names and property    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True,  blank=True)
    date_added = models.DateTimeField(auto_now_add=True)


    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return round(total, 2)

# Shipping model contains shipping field names and property   
class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    province = models.CharField(max_length=200, null=False)
    postalcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return self.address
    
    

ecommerce/CHBS/forms.py
from django import forms


class OrderForm(forms.Form):
    name = forms.CharField(label="Full Name", max_length=100)
    email = forms.EmailField(label="Email", max_length=100)
    number = forms.CharField(label="Phone Number", max_length=15)
    instruction = forms.CharField(label="Special Instructions", max_length=500)

ecommerce/CHBS/views.py
# Author: Taiwo Akinlabi
#Code sourced from : https://www.youtube.com/watch?v=obZMr9URmVI&list=PL-51WBLyFTg0omnamUjL1TCVov7yDTRng&index=2
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from decimal import *
import datetime
from .models import *
import json
from .utils import *
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from .forms import *
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.

def home(request):
    special_products = []
    products = Product.objects.all()
    for prod in products:
        if prod.special:
            special_products.append(prod)
    context = {'special_products': special_products[0:3]}
    return render(request, 'CHBS/home.html', context)

def menu(request):
    products  = Product.objects.all()
    context = {'products':products}
    return render(request, 'CHBS/menu_dev.html', context)

# view function for the homepage returns the page request, urls and context dictonary containing 
# The context dictonary contains values that can retrived from the database
# def homepage(request):
#     products  = Product.objects.all()
#     data = cartData(request)
#     cartItems = data['cartItems']
#     order = data['order']
#     context = {'products':products, 'order':order}
#     return render(request, 'CHBS/homepage.html', context)

# view function for the cart page returns the page request, urls and context dictonary
def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'CHBS/cart.html', context)

# view function for the menu page returns the page request, urls and context dictonary
# def menu(request):
#     products  = Product.objects.all()
#     context = {'products':products}
#     return render(request, 'CHBS/menu.html', context)

# view function for the contact page returns the page request, urls and context dictonary
def contact(request):
    context = {}
    return render(request, 'CHBS/contact.html', context)

# view function for the checkout page returns the page request, urls and context dictonary
def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            number = form.cleaned_data['number']
            instruction = form.cleaned_data['instruction']
            title = f'You got a order from {name}'
            message = f'You got an order from {name}\n- Phone number: {number}\n- Email: {email}\n- Special Instruction: {instruction}'
            send_mail(title, message, settings.EMAIL_HOST_USER, [settings.EMAIL_HOST_USER])
            return redirect('chbs:thank-you')
    
    context = {'items':items, 'order':order, 'cartItems':cartItems, 'form': form}
 
    return render(request, 'CHBS/checkout.html', context)

def thank_you_view(request):
    return render(request, 'CHBS/thank_you.html')

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete() 
    return JsonResponse('item was updated', safe=False)

# view function for the process_order page that processes both authenticated and unauthenticated users order and sends and email to the client 
def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        context = {'items':items,'order':order, 'customer':customer, }
        #holds email message in a html template then reders it as a string
        template = render_to_string('chbs/email_template.html', context)

        #email format and infomation 
        email = EmailMessage(
            'Subject',
            template,
            settings.EMAIL_HOST_USER,
            ['akin0045@algonquinlive.com'],
        )

        email.fail_silently=False
        # sends email
        email.send()

    else:
        customer, order, items = guestOrder(request, data)
        context = {'items':items,'order':order, 'customer':customer, }
         #holds email message in a html template then reders it as a string
        template = render_to_string('chbs/email_template.html', context)
                #email format and infomation 
        email = EmailMessage(
            'NEW ORDER:',
            template,
            settings.EMAIL_HOST_USER,
            ['akin0045@algonquinlive.com'],
        )

        email.fail_silently=False
        email.send()
    
    total = round(Decimal(data['form']['total']), 2)
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            province=data['shipping']['province'],
            postalcode=data['shipping']['postal'],
        )

    print(request.body)

    return JsonResponse('Payment complete!', safe=False)

ecommerce/templates/CHBS/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/cartsDS.css" %}">
    <style>
        .background-image-area {
  position: relative; 
  justify-content: center;
  height: 100vh;
  z-index: 1;
}

.background-image-area:before {
  content: ""; 
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-image: url('{% static 'images/bakedgoods.jpg' %}'); 
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  opacity: 0.4; 
  z-index: -1;
}

      </style>
</head>

<body>
    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img class="me-2" src="{% static 'images/CHBS_logo.png' %}"  width="30" height="30" alt="123">
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'chbs:home' %}" class="nav-link px-2 text-secondary">Home</a></li>
                    <li><a href="{% url 'chbs:menu' %}" class="nav-link px-2 text-white">Menu</a></li>
                    <li><a href="{% url 'chbs:contact' %}" class="nav-link px-2 text-white">Contact</a></li>
                </ul>

                <!-- <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
              <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
            </form> -->

                <div class="text-end d-flex">
                    <a href="{% url 'chbs:cart' %}" class="d-flex align-items-center px-2 mb-2 mb-lg-0 text-white text-decoration-none">
                        <svg xmlns="http://www.w3.org/2000/svg" width="49" height="32" fill="currentColor"
                            class="bi bi-cart4" viewBox="0 0 16 16">
                            <path
                                d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0" />
                        </svg>
                        <span id="cart-quantity" class="badge bg-danger rounded-circle" style="position: relative; top: -20px; right: 10px;">0</span>
                    </a>
                    <a href="{% url 'account_login' %}" class="btn btn-outline-light me-2">Login</a>
                </div>
            </div>
        </div>
    </header>
    {% block content %} {% endblock %}
    <footer class="d-flex justify-content-center align-items-center py-3 my-4 border-top">
        <div class="d-flex justify-content-center align-items-center w-100">
            <span class="text-body-secondary">© 2024 Country Home Baking & Sweets</span>
        </div>
    </footer>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
    <script type="text/javascript">
        let user = '{{request.user}}'
    </script>
</body>

</html>

ecommerce/templates/CHBS/cart.html
{% extends "CHBS/base.html" %}
{% load static %}
{% block content %}
        <section class="pt-5 pb-5">
          <div class="container">
            <div class="row w-100">
                <div class="col-lg-12 col-md-12 col-12">
                    <h3 class="display-5 mb-2 text-center" style="color:beige;"><b>Shopping Cart</b></h3>
                    <p style="color: beige;"> <i class="">{{order.get_cart_items}}</i> item(s) in your cart</p>
                    <table id="shoppingCart" class="table table-condensed table-responsive">
                        <thead>
                            <tr>
                                <th style="width:60%"><h>Product</h7></th>
                                <th style="width:12%">Price</th>
                                <th style="width:10%">Quantity</th>
                                <th style="width:16%">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in items %}
                            <tr>
                                <td data-th="Product">
                                    <div class="row">
                                        <div class="col-md-3 text-left">
                                            <img src="{{item.product.imageURL}}" alt="https://via.placeholder.com/250x250/5fa9f8/ffffff" class="img-fluid d-none d-md-block rounded mb-2 shadow ">
                                        </div>
                                        <div class="col-md-9 text-left mt-sm-2">
                                            <h3>{{item.product.name}}</h3>
                                            <p class="font-weight-light">Brand &amp; Name</p>
                                        </div>
                                    </div>
                                </td>
                                <td data-th="Price">${{item.product.price|floatformat:2}}</td>
                                <td data-th="Quantity">
                                    {% comment %} <input data-product={{ item.product.id}} name="quantity" type="number" class="form-control form-control-lg text-center quantityInput" value="{{item.quantity}}"> {% endcomment %}
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrowup.png' %}">
                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrowdown.png' %}">
                                    </div>
                              </td>
                                <td class="actions" data-th="">
                                    <div class="text-right">
                                        ${{item.get_total|floatformat:2}}
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
            <div id="cartoverlay" class="container">
                <p id="frontpara" class="totals">
                <b>Tax: {{order.get_cart_tax|floatformat:2}}</b><br>
                <b>Total:{{order.get_cart_total|floatformat:2}}</b><br><br>
                <br><br><a class="btn btn-dark" href="{% url 'chbs:checkout' %}" id="checkout">Checkout</a>    
                <br><br><a class="btn btn-dark" href="{% url 'chbs:menu' %}">&#8592; Continue Shopping</a>  
            </p>
            </div>    
        </div>
      </div>
    </section>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
        <script type="text/javascript">
            let user = '{{request.user}}'
        </script>
{% endblock %}

ecommerce/templates/CHBS/checkout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/checkoutDS.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/cartsDS.css" %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Sachleen Kaur">
    <meta name="email" content="kaur0777@algonquinlive.com">
    <script type="text/javascript">
        {% comment %} Code sourced from : https://www.youtube.com/watch?v=obZMr9URmVI&list=PL-51WBLyFTg0omnamUjL1TCVov7yDTRng&index=2 {% endcomment %}
        var user = '{{request.user}}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getToken('csrftoken');

        function getCookie(name) {
            //Split cookie string and get all individual name=value pair in an array
            var cookieArr = document.cookie.split(";");

            //loop through the array elements 
            for(var i=0; i<cookieArr.length; i++){
                var cookiePair = cookieArr[i].split("=");

                /*Removing whitespace at the beginning of the cookie name and
                compare it with the given string */
                if(name == cookiePair[0].trim()){
                    //Decode the cookie valye and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }

            //Return null if not found
            return null;
        }
        var cart = JSON.parse(getCookie('cart'))

        if(cart == undefined){
            cart = {}
            console.log('cart was created')
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }

        console.log('Cart;', cart )
    </script>
    <!-- <script src="inspiration.js"></script> -->
    <title>Checkout Page</title>
</head>

<body class="container" style="background-image: url('{% static "images/backcupcake.jpg" %}'); 
background-position: center;">



    <div class="container" >
        <h1 style="text-align: center; color: aliceblue;">Checkout</h1>
        <div class="col-75">
            <div class="container" >
                <a class="btn btn-secondary" href="{% url 'chbs:cart' %}">&#8592; Back to cart</a>
                <br><br>
                <form action="{% url 'chbs:checkout' %}" id="form" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-25">
                            <div class="container" style="background-color: aliceblue;">
                                <h4>Cart
                                    <span class="price" style="color:black">
                                        <i class="fa fa-shopping-cart"></i>
                                        <b>{{order.get_cart_items}}</b>
                                    </span>
                                </h4>
                                {% for item in items %}
                                <p><strong>{{item.product.name}} [{{item.quantity}}]</strong> <span class="price">${{item.get_total|floatformat:2}}</span></p>
                               
                                {% endfor %}
                                <hr>
                                <!-- <p>Subtotal <span class="subtotal price" style="color:#c59a6c"><b>${{order.get_cart_subtotal|floatformat:2}}</b></span></p>
                                <p>Taxes & other fees <span class="price" style="color:#c59a6c"><b>${{order.get_cart_tax|floatformat:2}}</b></span></p> -->
                                <p>Total <span class="price" style="color:#c59a6c"><b>${{order.get_cart_total|floatformat:2}}</b></span></p>
                            </div>
                            <div class="box-element hidden" id="payment-info">
                                <small style="text-align: center;">Payment Option</small>
                                <button class="btn" id="make-payment"> Make Payment</button>
                            </div>
                        </div>

                       

                        <div class="col-50" id="form-wrapper">
                            <h2 style="color: #f7f7f7;">Billing Address</h2>
                            <div id="user-info" >
                            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
                            <input type="text" id="fname" name="name" placeholder="Meghan M. Doe" required>
                            <label for="email"><i class="fa fa-envelope"></i> Email</label>
                            <input type="text" id="email" name="email" placeholder="meghan@example.com" required>
                            <label for="phone"><i class="fa fa-phone"></i> Phone Number</label>
                            <input type="tel" id="phone" name="number" placeholder="000 000 0000" required>
                            <label for="myText"> <i class="fa fa-envelope"></i> Special Instructions:</label>
                            <input type="text" id="myText" name="instruction" placeholder="Allergies, dietary restrictions, notes.">
                        </div>
                            <div id="shipping-info">
                            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
                            <input type="text" id="adr" name="address" placeholder="1385 Woodroffe Ave" required>
                            <label for="city"><i class="fa fa-institution"></i> City</label>
                            <input type="text" id="city" name="city" placeholder="Ottawa" required>
                            

                            <div class="row">
                                <div class="col-55">
                                  <label for="province">Province</label>
                                  <input type="text" id="province" name="province" placeholder="NY" required>
                                </div>
                                <div class="col-55">
                                  <label for="postal">Postal Code</label>
                                  <input type="text" id="postal" name="postal" placeholder="10001" required>
                                </div>
                              
                            </div>
                        </div>

                    </div>
                    <input id="form-button" type="submit" value="Continue to checkout" class="btn" >
                </form>
            </div>
        </div>


    </div>

    <script type="text/javascript">
        {% comment %} Code sourced from : https://www.youtube.com/watch?v=obZMr9URmVI&list=PL-51WBLyFTg0omnamUjL1TCVov7yDTRng&index=2 {% endcomment %}
        var shipping = '{{order.shipping}}'
        var total = "{{order.get_cart_total}}"
        var cartItems = "{{order.get_cart_items}}"

        if(shipping == 'False'){
            document.getElementById('shipping-info').innerHTML = ''
        }

        if( user != 'AnonymousUser'){
            document.getElementById('user-info').innerHTML = ''
            
        }

        if(shipping == 'False' && user != 'AnonymousUser'){
            document.getElementById('form-wrapper').classList.add("hidden");
            document.getElementById('payment-info').classList.remove("hidden");
        }

        if(cartItems == 0 && (user != 'AnonymousUser' || user == 'AnonymousUser')){
            document.getElementById('form-wrapper').classList.add("hidden");
            document.getElementById('form-button').classList.add("hidden");
            document.getElementById('payment-info').classList.add("hidden");
        }

        // var form = document.getElementById('form')
        // form.addEventListener('submit', function(e){
        //     e.preventDefault()
        //     console.log('Form Submitted...')
        //     document.getElementById('form-button').classList.add('hidden')
        //     document.getElementById('payment-info').classList.remove('hidden')
        // })

        document.getElementById('make-payment').addEventListener('click', function(e){
            e.preventDefault()
            submitFormData()
        })

        // send the form data to the backemd to process the order
        function submitFormData(){
            console.log('Payment button clicked')

            // stores user data
            var userFormData = {
                'name': null,
                'email': null,
                'phone': null,
                'total':total
            }

            // stores users shipping data
            var shippingInfo = {
                'address': null,
                'city': null,
                'province':null,
                'postal':null,
            }

            if (shipping != 'False'){
                shippingInfo.address = form.address.value
                shippingInfo.city = form.city.value
                shippingInfo.province = form.province.value
                shippingInfo.postal = form.postal.value
            }

            
            if(user == 'AnonymousUser'){
                userFormData.name = form.fullname.value
                userFormData.phone = form.phone.value
                userFormData.email = form.email.value
            }

            var url = '/process_order/'
            fetch(url, {
                method:'POST',
                headers:{
                    'Content-Type':'application/json', 
                    'X-CSRFToken': csrftoken, 
                },
                body:JSON.stringify({'form': userFormData, 'shipping': shippingInfo})
            })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                alert('Transaction completed');

                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
                window.location.href = "{% url 'chbs:home' %}"
            })
        }
    </script>
</body>
</html>